//! Languages and themes supported by Ranger.
//!
//! The UI string translation tables live on the `ranger-gui` side (coupled
//! to the structs generated by Slint). Here we only define the enums
//! and their TOML serialization for persistence in `config.toml`.

use serde::{Deserialize, Serialize};

/// Interface language. The user can change it in Settings; persisted
/// in `config.toml` (`language = "fr"` etc.).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum Lang {
    #[default]
    En,
    Fr,
    Es,
    De,
    It,
}

impl Lang {
    /// Short ISO 639-1 identifier.
    pub fn code(self) -> &'static str {
        match self {
            Lang::En => "en",
            Lang::Fr => "fr",
            Lang::Es => "es",
            Lang::De => "de",
            Lang::It => "it",
        }
    }

    /// Name of the language in its own language (Settings selector).
    pub fn native_name(self) -> &'static str {
        match self {
            Lang::En => "English",
            Lang::Fr => "Français",
            Lang::Es => "Español",
            Lang::De => "Deutsch",
            Lang::It => "Italiano",
        }
    }

    /// All supported languages, in display order.
    pub fn all() -> &'static [Lang] {
        &[Lang::En, Lang::Fr, Lang::Es, Lang::De, Lang::It]
    }

    /// Parses an ISO code; falls back to `En` if unrecognized.
    pub fn from_code(code: &str) -> Lang {
        match code {
            "fr" => Lang::Fr,
            "es" => Lang::Es,
            "de" => Lang::De,
            "it" => Lang::It,
            _ => Lang::En,
        }
    }
}

/// Interface theme preference. `Auto` follows the system theme.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum Theme {
    #[default]
    Auto,
    Light,
    Dark,
}

impl Theme {
    pub fn code(self) -> &'static str {
        match self {
            Theme::Auto => "auto",
            Theme::Light => "light",
            Theme::Dark => "dark",
        }
    }

    pub fn all() -> &'static [Theme] {
        &[Theme::Auto, Theme::Light, Theme::Dark]
    }

    pub fn from_code(code: &str) -> Theme {
        match code {
            "light" => Theme::Light,
            "dark" => Theme::Dark,
            _ => Theme::Auto,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_is_english() {
        assert_eq!(Lang::default(), Lang::En);
    }

    #[test]
    fn lang_code_round_trip() {
        for lang in Lang::all() {
            assert_eq!(Lang::from_code(lang.code()), *lang);
        }
    }

    #[test]
    fn lang_unknown_falls_back_to_english() {
        assert_eq!(Lang::from_code("zh"), Lang::En);
        assert_eq!(Lang::from_code(""), Lang::En);
    }

    #[test]
    fn theme_default_is_auto() {
        assert_eq!(Theme::default(), Theme::Auto);
    }

    #[test]
    fn theme_code_round_trip() {
        for t in Theme::all() {
            assert_eq!(Theme::from_code(t.code()), *t);
        }
    }
}
